from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel
from typing import Optional, List, Dict, Any
from services.thesis_service import (
    get_thesis_intelligence,
    generate_dynamic_thesis,
    generate_ai_grounded_thesis,
    process_thesis_copilot_command,
    generate_grounded_thesis_summary,
    AI_THESIS_CACHE
)

router = APIRouter(prefix="/api/thesis", tags=["Thesis Intelligence Engine"])

class ThesisAnalyzeRequest(BaseModel):
    symbol: str
    claim: Optional[str] = None
    horizon_months: Optional[int] = 24

class ThesisCopilotRequest(BaseModel):
    query: str
    active_symbol: Optional[str] = "RELIANCE"
    history: Optional[List[Dict[str, str]]] = []

@router.get("/{symbol}")
async def get_stock_thesis(symbol: str, refresh: Optional[bool] = False):
    """Returns the point-in-time thesis intelligence object dynamically generated by AI."""
    clean = (symbol or "RELIANCE").upper().strip().replace(".NS", "").replace(".BO", "")
    if not refresh and clean in AI_THESIS_CACHE:
        return AI_THESIS_CACHE[clean]
    
    # Dynamically generate grounded thesis using Gemini AI + real market telemetry
    data = await generate_ai_grounded_thesis(clean)
    if not data:
        data = get_thesis_intelligence(clean)
    return data

@router.post("/recheck/{symbol}")
async def recheck_stock_thesis(symbol: str):
    """Triggers deep point-in-time AI re-evaluation of company thesis against live market filings."""
    clean = (symbol or "RELIANCE").upper().strip().replace(".NS", "").replace(".BO", "")
    if clean in AI_THESIS_CACHE:
        del AI_THESIS_CACHE[clean]
    data = await generate_ai_grounded_thesis(clean)
    return data

@router.post("/analyze")
async def analyze_custom_thesis(req: ThesisAnalyzeRequest):
    """Compiles a natural language thesis into a structured hypothesis with deterministic scoring via Gemini AI."""
    if not req.symbol:
        raise HTTPException(status_code=400, detail="Stock symbol is required")
    data = await generate_ai_grounded_thesis(req.symbol, req.claim)
    return data

@router.post("/copilot-query")
async def query_thesis_copilot(req: ThesisCopilotRequest):
    """Processes natural language voice/copilot commands, executes financial reasoning, and returns UI actions."""
    if not req.query:
        raise HTTPException(status_code=400, detail="Query string is required")
    res = await process_thesis_copilot_command(
        query=req.query,
        active_symbol=req.active_symbol,
        history=req.history
    )
    return res

